#!/bin/bash

function deploy_maintenance_page() {
  echo "Updating service..."
  aws ecs update-service --service "${ECS_SERVICE}_web" --cluster ${ECS_CLUSTER} --task-definition "si_maintenance" --region ${AWS_REGION}
  echo "Waiting for service deployment to complete..."
  aws ecs wait services-stable --cluster ${ECS_CLUSTER} --services "${ECS_SERVICE}_web" --region ${AWS_REGION}
}

function create_cloudfront_invalidation() {
  echo "Creating cloudfront invalidation"
  INVALIDATION_ID=$(aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*" --region $AWS_REGION | jq -r '.Invalidation.Id' )
  aws cloudfront wait invalidation-completed --id $INVALIDATION_ID --distribution-id $CLOUDFRONT_DISTRIBUTION_ID
}

deploy_maintenance_page
create_cloudfront_invalidation

